name: flutter_application_1
description: A new Flutter project.
publish_to: 'none' # This prevents publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.7.0 <4.0.0"  # More complete format for Dart SDK range

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  fl_chart: ^0.70.2
  sqflite: ^2.2.6
  path_provider: ^2.1.2
  dots_indicator: ^4.0.1  # ✅ fixed typo: was dots_indicotor
  get: ^4.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/Logos/log.webp
    - assets/Images/background.jpg
    - assets/Images/login.jpg
    - assets/Images/food1.png
    - assets/Images/food2.jpg
    - assets/Images/fruit.jpg
    - assets/Images/drink.png
    - assets/Images/ejf.png
